### ISSUE TITLE
Location not set in crate.js

### ISSUE THREAD

**Issue by RobRademeyer** [Galavantier/crate.js#1]
I really want to use Crate...

However, I am continually flummoxed by "location" on line 39 of crate.js i.e. 
`location.appendChild(el);`

Regardless of browser used [or the options set], I always get the following error:
`TypeError: location is null`

**Comment by lincolnluxor** [comment]
The most likely cause is that the element you set as `setParent:` in the JSON isn't being found.  Easy test for this would be to remove setParent and see if it loads using the body of the document (see line 59)

**Comment by RobRademeyer** [comment]
Hello Adam Tate 

Thanks for the reply... 

I'm not convinced this is the problem. I tried your sample Options
object viz. 
 var crateOptions = {'setBody':'Some string for my message box!'};
and I still get the error. 

Attached is a screenshot of the debugger in FireFox - perhaps that will
give you some more insight into the problem? 

Thanks
R 

On 2015-03-19 7:33 pm, Adam Tate wrote: 

> The most likely cause is that the element you set as setParent: in the JSON isn't being found. Easy test for this would be to remove setParent and see if it loads using the body of the document (see line 59) 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/Galavantier/crate.js/issues/1#issuecomment-83688336

**Comment by lincolnluxor** [comment]
Sadly, I don't see an attached file here on github.  I'm assuming you responded through email?  It doesn't send me the attachments that way.  Can you upload the image to a image host and post a link? Better option: Could I possibly see your exact implementation of the code?

Also, I tested the sample you posted `var crateOptions = {'setBody':'Some string for my message box!'};  crate.init(crateOptions);` and it worked just fine. 

This is throwing me for a loop that I can recreate this.

**Comment by RobRademeyer** [comment]
Hi Adam 

Thanks for the reply & apologies for the tardy response - I was away
from the weekend... 

The first problem can be seen at www.rob.co.za/crate/sample01.html [2].
This problem arises when the call to crate is included in the <head>
section [you can inspect the code]. 

The second problem can be seen at www.rob.co.za/crate/sample02.html [3].
This problem arises when the call to crate is included in the <body>
section [you can inspect the code]. 

Your input will be greatly appreciated... 

Later
R 

On 2015-03-20 3:44 am, Adam Tate wrote: 

> Sadly, I don't see an attached file here on github. I'm assuming you responded through email? It doesn't send me the attachments that way. Can you upload the image to a image host and post a link? Better option: Could I possibly see your exact implementation of the code? 
> 
> Also, I tested the sample you posted var crateOptions = {'setBody':'Some string for my message box!'}; crate.init(crateOptions); and it worked just fine. 
> 
> This is throwing me for a loop that I can recreate this. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/Galavantier/crate.js/issues/1#issuecomment-83847943
[2] http://rob.co.za/crate/sample01.html
[3] http://rob.co.za/crate/sample02.html

**Comment by lincolnluxor** [comment]
No worries.  Hope you enjoyed your time away.

It seems to work just fine for me when I ran it `crate.init({'setBody':'test'}` in the console.  Have you tried moving the script to the bottom of the body tag?  It would make sense that it doesn't work in the head since no DOM has been loaded yet, it doesn't know where to attach.  Also it doesn't contain a built in onload function.

Also, don't forget to style that bad boy!  Feel free to steal the css I use on the preview and modify to your liking.

That makes me think I should have a separate css file for people to use also...

**Comment by RobRademeyer** [comment]
Thanks, Adam... 

Where is your "preview" i.e. where can I see an online, working version?

R 

On 2015-03-24 12:10 am, Adam Tate wrote: 

> No worries. Hope you enjoyed your time away. 
> 
> It seems to work just fine for me when I ran it crate.init({'setBody':'test'} in the console. Have you tried moving the script to the bottom of the body tag? It would make sense that it doesn't work in the head since no DOM has been loaded yet, it doesn't know where to attach. Also it doesn't contain a built in onload function. 
> 
> Also, don't forget to style that bad boy! Feel free to steal the stylings I use on the preview and modify to your liking. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/Galavantier/crate.js/issues/1#issuecomment-85225872

**Comment by lincolnluxor** [comment]
The crate maker tool uses crate. You can see it here: http://galavantier.github.io/crate.js/cratemaker.html

**Comment by lincolnluxor** [comment]
I'm going to consider this closed since the library was working in your example. Feel free to let me know if you need anymore help.
